version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recipe-etl-stack"
region = "us-east-2"
profile = "etl-demo"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
s3_prefix = "recipe-etl-stack"
image_repositories = []
parameter_overrides = "Environment=\"dev\" RDSPostgreSQLHost=\"localhost\" RDSPostgreSQLPort=\"5432\" RDSPostgreSQLDBName=\"postgres\" RDSPostgreSQLUsername=\"postgres\" RDSPostgreSQLPassword=\"postgres\" RDSPostgreSQLSchema=\"public\" RDSPostgreSQLTable=\"recipes\""
